name: setup
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: make setup
      - run: make start
      - run: make lint
      - name: run tests
        run: make test
